-- YOUR CODE GOES HERE
-- CREATE YOUR DATABASE
-- CREATE YOUR TABLES
-- ADD RECORDS TO YOUR TABLE


DROP DATABASE IF EXISTS mamaLeesFlavors;
CREATE DATABASE mamaLeesFlavors;

USE mamaLeesFlavors;

CREATE TABLE Flavors(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  Ingredients VARCHAR(255),
  IsVegan TINYINT(1),
  IsTeaFlavor TINYINT(1),
  ImageName VARCHAR(255),
  PRIMARY KEY (ID)
);

--LOAD DATA LOCAL INFILE '/Users/esmy/Dev/projects/MamaLeesData.csv' INTO TABLE Flavors FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;